### ISSUE TITLE
Criar página de Adicionar Bem

### ISSUE THREAD

**Issue by marcosvitor1994** [marcosvitor1994/projetoMobile#10]
A página deverá conter:
Menu
Botão de Logout
Título
Input de ID
Input de Quantidade
Input de Descricão 
Botão de Salvar

**Comment by Roberta-Oliveira** [comment]
![image](https://user-images.githubusercontent.com/70297387/162628326-a689e322-0892-4bcf-836a-c202a85990a0.png)

**Comment by Roberta-Oliveira** [comment]
Página criada.

**Comment by marcosvitor1994** [comment]
Aprovado.
