### ISSUE TITLE
Erro de nomenclatura "Estoque"

### ISSUE THREAD

**Issue by marcosvitor1994** [marcosvitor1994/projetoMobile#11]
Na tela pós Login,  tem um erro de nomenclatura: 

Alterar "Estoque"
Para "Inventário"

**Comment by marcosvitor1994** [comment]
![Captura de Tela 2022-04-12 às 19 35 56](https://user-images.githubusercontent.com/70297708/163065928-e82671e3-3cb3-42b7-90c4-433b953ae247.png)

**Comment by marcosvitor1994** [comment]
Alterado

**Comment by Roberta-Oliveira** [comment]
Aprovado!
