### ISSUE TITLE
Criar Protótipo no FIGMA

### ISSUE THREAD

**Issue by marcosvitor1994** [marcosvitor1994/projetoMobile#2]

**Comment by Roberta-Oliveira** [comment]
![Captura de Tela 2022-04-08 às 20 59 20](https://user-images.githubusercontent.com/70297387/162548387-a7d05a71-a1aa-49f0-91cd-0decb29710f7.png)

**Comment by Roberta-Oliveira** [comment]
Projeto criado.

**Comment by marcosvitor1994** [comment]
Aprovado
