### ISSUE TITLE
Criar projeto no FIGMA

### ISSUE THREAD

**Issue by marcosvitor1994** [marcosvitor1994/projetoMobile#3]

**Comment by Roberta-Oliveira** [comment]
![image](https://user-images.githubusercontent.com/70297387/162628425-a5809a2e-60f3-4a8c-86b3-aa7c621c8403.png)

**Comment by Roberta-Oliveira** [comment]
Projeto criado.

**Comment by marcosvitor1994** [comment]
Aprovado
