### ISSUE TITLE
Criar Tipografia no Figma

### ISSUE THREAD

**Issue by marcosvitor1994** [marcosvitor1994/projetoMobile#4]
Escolher fonte 
Decidir tamanho de fontes

**Comment by marcosvitor1994** [comment]
![Captura de Tela 2022-04-08 às 21 19 15](https://user-images.githubusercontent.com/70297708/162548830-c2aa12d1-f0c0-44ee-bbab-3e20153f49c4.png)

**Comment by marcosvitor1994** [comment]
Criado

**Comment by Roberta-Oliveira** [comment]
Aprovado!
