### ISSUE TITLE
Criar padrão de cores

### ISSUE THREAD

**Issue by marcosvitor1994** [marcosvitor1994/projetoMobile#5]
Quais cores serão predominantes no app

**Comment by marcosvitor1994** [comment]
![Captura de Tela 2022-04-08 às 21 17 11](https://user-images.githubusercontent.com/70297708/162548745-b10daf35-d695-454c-b500-667d08314312.png)

**Comment by marcosvitor1994** [comment]
Criado

**Comment by Roberta-Oliveira** [comment]
Aprovado!
