### ISSUE TITLE
Botões e Input's

### ISSUE THREAD

**Issue by marcosvitor1994** [marcosvitor1994/projetoMobile#6]
Criar botão de login
Criar botão de adicionar bem
Criar botão de editar bem
Criar botão de Salvar bem
Criar input de login
Criar input de editar bem
Criar input de adicionar bem

**Comment by marcosvitor1994** [comment]
![Captura de Tela 2022-04-08 às 21 15 31](https://user-images.githubusercontent.com/70297708/162548646-89de5685-bf50-4177-81b0-fe1a0d411fda.png)

**Comment by marcosvitor1994** [comment]
Criado

**Comment by Roberta-Oliveira** [comment]
Aprovado!
