### ISSUE TITLE
Criar página de Login

### ISSUE THREAD

**Issue by marcosvitor1994** [marcosvitor1994/projetoMobile#7]
A página de login deverá conter:
Marca da empresa
Campo para inserir email
Campo para inserir senha
Botão para realizar o Login

**Comment by marcosvitor1994** [comment]
![Captura de Tela 2022-04-08 às 21 07 17](https://user-images.githubusercontent.com/70297708/162548368-a17ae52f-3298-4e0f-8c88-78854366fa48.png)

**Comment by marcosvitor1994** [comment]
Criado

**Comment by Roberta-Oliveira** [comment]
Aprovado!
