### ISSUE TITLE
Criar página de Inventário

### ISSUE THREAD

**Issue by marcosvitor1994** [marcosvitor1994/projetoMobile#8]
A página deverá conter: 
Menu 
Botão de Logout 
Título da página 
Tabela de bens
Botão de editar bem
Botão de adicionar bem

**Comment by Roberta-Oliveira** [comment]
![image](https://user-images.githubusercontent.com/70297387/162628610-78a03915-e299-4c61-b694-88704273aaf7.png)

**Comment by Roberta-Oliveira** [comment]
Página criada.

**Comment by marcosvitor1994** [comment]
Aprovado
