### ISSUE TITLE
Criar página de Editar Bem

### ISSUE THREAD

**Issue by marcosvitor1994** [marcosvitor1994/projetoMobile#9]
A página deverá conter:
Menu
Botão de Logout
Título 
Dados do bem
Botão de Salvar

**Comment by Roberta-Oliveira** [comment]
![image](https://user-images.githubusercontent.com/70297387/162628102-919aa6bc-26c6-43f5-85c6-5153717f2f88.png)

**Comment by Roberta-Oliveira** [comment]
Pagina criada.

**Comment by marcosvitor1994** [comment]
Aprovado.
